version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    restart: always